#!/bin/bash

if [[ -f /opt/redacto-kms/tls/tls.crt ]] && [[ -f /opt/redacto-kms/tls/tls.key ]]; then
  echo "Redacto KMS TLS key and certificate already exist. Exiting."
  exit 0
fi

echo "Generating Redacto KMS TLS key and self-signed certificate..."

# Create TLS and Data directory
mkdir --parents /opt/redacto-kms/tls
mkdir --parents /opt/redacto-kms/data

# Generate TLS key and certificate
cd /opt/redacto-kms/tls
openssl req \
  -out tls.crt \
  -new \
  -keyout tls.key \
  -newkey rsa:4096 \
  -nodes \
  -sha256 \
  -x509 \
  -subj "/O=Redacto KMS/CN=Redacto KMS" \
  -days 1095 # 3 years

# Update file permissions
chown --recursive redacto-kms:redacto-kms /etc/redacto-kms
chown --recursive redacto-kms:redacto-kms /opt/redacto-kms
chmod 600 /opt/redacto-kms/tls/tls.crt /opt/redacto-kms/tls/tls.key
chmod 700 /opt/redacto-kms/tls

echo "Redacto KMS TLS key and self-signed certificate have been generated in '/opt/redacto-kms/tls'."

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
